server:
  port: 8091

spring:
  application:
    name: consumer-application
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/

#开启feign hystrix支持
feign:
  hystrix:
    enabled: true

#监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /



